---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    permissions:
      actions: read
      contents: write
      pull-requests: write
      packages: read
      security-events: write
    uses: lazytarget/ha-workflows/.github/workflows/addon-ci.yaml@main
